#ifndef MODEL_CONSTANTS_DEFAULTS_H
#define MODEL_CONSTANTS_DEFAULTS_H

#define CONST_DEF_OPTIONS_STATE_GAMES 1000000
#define CONST_DEF_OPTIONS_CURTAINS 3
#define CONST_DEF_OPTIONS_LOG_HEADER true

#endif
