#ifndef MODEL_ENUM_STATE_TYPE_H
#define MODEL_ENUM_STATE_TYPE_H

enum EnumStateType {
    STATE_TYPE_NOTHING,
    STATE_TYPE_DO_HOST_REVEAL,
    STATE_TYPE_DO_HOST_REVEAL_DO_PLAYER_SWITCH,
    STATE_TYPE_DO_PLAYER_CHANGE
};

#endif
